jQuery(document).ready(function () {
    jQuery("body").click(function (e) {
        let id = e.target.id
        if (id === "d") {
            $("html").removeClass("cur-1")
            $("button").removeClass("cur-1")
            $("label").removeClass("cur-1")
            $("html").removeClass("cur-2")
            $("button").removeClass("cur-2")
            $("label").removeClass("cur-2")
            $("html").removeClass("cur-3")
            $("button").removeClass("cur-3")
            $("label").removeClass("cur-3")
            $("html").removeClass("cur-4")
            $("button").removeClass("cur-4")
            $("label").removeClass("cur-4")
        }
        if (id === "1") {
            $("html").addClass("cur-1")
            $("button").addClass("cur-1")
            $("label").addClass("cur-1")
            $("html").removeClass("cur-2")
            $("button").removeClass("cur-2")
            $("label").removeClass("cur-2")
            $("html").removeClass("cur-3")
            $("button").removeClass("cur-3")
            $("label").removeClass("cur-3")
            $("html").removeClass("cur-4")
            $("button").removeClass("cur-4")
            $("label").removeClass("cur-4")
        }
        if (id === "2") {
            $("html").addClass("cur-2")
            $("button").addClass("cur-2")
            $("label").addClass("cur-2")
            $("html").removeClass("cur-1")
            $("button").removeClass("cur-1")
            $("label").removeClass("cur-1")
            $("html").removeClass("cur-3")
            $("button").removeClass("cur-3")
            $("label").removeClass("cur-3")
            $("html").removeClass("cur-4")
            $("button").removeClass("cur-4")
            $("label").removeClass("cur-4")
        }
        if (id === "3") {
            $("html").addClass("cur-3")
            $("button").addClass("cur-3")
            $("label").addClass("cur-3")
            $("html").removeClass("cur-1")
            $("button").removeClass("cur-1")
            $("label").removeClass("cur-1")
            $("html").removeClass("cur-2")
            $("button").removeClass("cur-2")
            $("label").removeClass("cur-2")
            $("html").removeClass("cur-4")
            $("button").removeClass("cur-4")
            $("label").removeClass("cur-4")
        }
        if (id === "4") {
            $("html").addClass("cur-4")
            $("button").addClass("cur-4")
            $("label").addClass("cur-4")
            $("html").removeClass("cur-1")
            $("button").removeClass("cur-1")
            $("label").removeClass("cur-1")
            $("html").removeClass("cur-2")
            $("button").removeClass("cur-2")
            $("label").removeClass("cur-2")
            $("html").removeClass("cur-3")
            $("button").removeClass("cur-3")
            $("label").removeClass("cur-3")
        }
    })
})